services:
  juice-shop:
    image: bkimminich/juice-shop
    container_name: juice-shop
    restart: unless-stopped
    networks:
      - juice_net
    ports:
      - "3000:3000"

networks:
  juice_net:
    external: true